## 异常
Dart 代码可以抛出和捕获异常。异常是表明发生意外情况的错误。如果异常未被捕获，抛出该异常的 `isolate` 会被挂起，通常该 `isolate` 及其程序会终止。
与 Java 不同，Dart 的所有异常都是未检查异常。方法不会声明可能抛出哪些异常，并且不要求你捕获任何异常。
Dart 提供了 `Exception` 和 `Error` 类型，以及许多预定义的子类型。当然，你也可以定义自己的异常。不过，Dart 程序可以将任何非空对象（不仅仅是 `Exception` 和 `Error` 对象）作为异常抛出。

#### Throw
以下是抛出（或引发）异常的一个示例：
```dart
throw FormatException('Expected at least 1 section');
```
你也可以抛出任意对象：
```dart
throw 'Out of llamas!';
```

因为抛出异常是一个表达式，所以你可以在 => 语句中以及任何允许表达式的地方抛出异常：
```dart
void distanceTo(Point other) => throw UnimplementedError();
```

#### Catch和on
捕获异常会阻止异常继续传播（除非你重新抛出该异常）。捕获异常为你提供了处理它的机会：
```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
}
```

要处理可能抛出多种类型异常的代码，可以指定多个 `catch` 子句。第一个匹配所抛出对象类型的 `catch` 子句会处理该异常。如果 `catch` 子句未指定类型，则该子句可以处理任何类型的抛出对象：
```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  // A specific exception
  buyMoreLlamas();
} on Exception catch (e) {
  // Anything else that is an exception
  print('Unknown exception: $e');
} catch (e) {
  // No specified type, handles all
  print('Something really unknown: $e');
}
```

如前面的代码所示，你可以使用 `on` 或 `catch`，或者两者一起使用。当需要指定异常类型时，使用 `on`；当异常处理程序需要异常对象时，使用 `catch`。
你可以为 `catch()` 指定一个或两个参数。第一个参数是抛出的异常，第二个参数是堆栈跟踪（`StackTrace` 对象）。
```dart
try {
  // ···
} on Exception catch (e) {
  print('Exception details:\n $e');
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

要部分处理异常并允许其继续传播，请使用 `rethrow` 关键字。
```dart
void misbehave() {
  try {
    dynamic foo = true;
    print(foo++); // Runtime error
  } catch (e) {
    print('misbehave() partially handled ${e.runtimeType}.');
    rethrow; // Allow callers to see the exception.
  }
}

void main() {
  try {
    misbehave();
  } catch (e) {
    print('main() finished handling ${e.runtimeType}.');
  }
}
```

#### Finally
为确保无论是否抛出异常都能运行某些代码，请使用 `finally` 子句。如果没有 `catch` 子句匹配该异常，异常会在 `finally` 子句执行后继续传播：
```dart
try {
  breedMoreLlamas();
} finally {
  // Always clean up, even if an exception is thrown.
  cleanLlamaStalls();
}
```

`finally` 子句会在任何匹配的 `catch` 子句之后执行：
```dart
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // Handle the exception first.
} finally {
  cleanLlamaStalls(); // Then clean up.
}
```

## 断言(Assert)
在开发过程中，可使用 `assert` 语句 ——`assert(<条件>, <可选消息>)`;—— 当布尔条件为 `false` 时中断正常执行。
```dart
// Make sure the variable has a non-null value.
assert(text != null);

// Make sure the value is less than 100.
assert(number < 100);

// Make sure this is an https URL.
assert(urlString.startsWith('https'));
```

要为断言附加消息，请将字符串作为第二个参数添加到 `assert` 中（可选地在末尾添加逗号）：
```dart
assert(
  urlString.startsWith('https'),
  'URL ($urlString) should start with "https".',
);
```

`assert` 的第一个参数可以是解析为布尔值的任意表达式。如果表达式的值为 `true`，则断言成功，执行继续；如果为 `false`，则断言失败并抛出异常（AssertionError）。
断言究竟何时生效？这取决于你使用的工具和框架：
- Flutter 在调试模式下启用断言。
- 仅用于开发的工具（如 `webdev serve`）通常默认启用断言。
- 某些工具（如 `dart run` 和 `dart compile js`）通过命令行标志 `--enable-asserts` 支持断言。

在生产代码中，断言会被忽略，且 `assert` 的参数不会被求值。
